name: KanaCustomMachine
version: '${project.version}'
main: fr.kaname.KanaCustomMachine.KanaCustomMachine
api-version: '1.20'
author: "Kaname"
description: "Custom Machine"

commands:
  custommachines:
    permission: itemplugin.kanaitem
    aliases:
      - cm
